version: '3'

services:
  postgres:
    container_name: it-manager-pg
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   container_name: raid-x-redis
  #   image: redis:alpine
  #   ports:
  #     - '6379:6379'

  # mongo:
  #   container_name: raid-x-mongo
  #   image: mongo
  #   ports:
  #     - '27017:27017'

  # mailhog:
  #   container_name: raid-x-mailhog
  #   image: mailhog/mailhog
  #   ports:
  #     - '8025:8025'
  #     - '1025:1025'
volumes:
  postgres_data:
