version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  release-job:
    docker:
      - image: circleci/node:16
    steps:
      - add_ssh_keys:
          fingerprints:
            - '18:8f:16:67:5e:7f:c4:a0:5b:f4:88:d5:93:47:86:c6'
      - checkout
      - restore_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
      - restore_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: 'Configure git'
          command: |
            git config user.email "jvictorsantos852@gmail.com"
            git config user.name "thejoaov"
            yarn config set version-git-tag true
            yarn config set version-commit-hooks false
            yarn config set version-git-message "[skip ci] v%s"
      - run:
          name: 'Install dependencies'
          command: 'yarn'
      - save_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - save_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn
      - run:
          name: 'Generate version'
          command: |
            yarn version --patch
            version_name=$(node -pe "require('./package.json').version")
            git add . && git commit -m "[skip ci] bump version to ${version_name}" --no-verify
      - run:
          name: Create release
          command: |
            git push -q git@github.com:thejoaov/it-manager-server.git v${version_name} HEAD:master --force
            git push -q git@github.com:thejoaov/it-manager-server.git v${version_name} --force

  test-job:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
      - restore_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: 'Install dependencies'
          command: 'yarn'
      - run:
          name: 'Run linter'
          command: 'yarn lint'
      - run:
          name: 'Run tests and get coverage'
          command: 'yarn coverage'
      - save_cache:
          key: 'node-v1-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - save_cache:
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ~/.cache/yarn
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/lcov-report

workflows:
  test-workflow:
    jobs:
      - test-job

  deploy-workflow:
    jobs:
      - test-job:
          filters: &deploy_filter
            branches:
              only: master
      - release-job:
          filters: *deploy_filter
          requires:
            - test-job
