name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: comment, report-markdown
          package-manager: yarn
          prnumber: ${{ steps.findPr.outputs.number }}
      # - uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     message: ${{ steps.coverage.outputs.report }}
